### PR TITLE
feat(dagwriter): Updated dependencies and refactored DagWriter and DagBatchWriter to match that

### PR DESCRIPTION
**Pull request by drgomesp**
Updated dependencies and refactored DagWriter and DagBatchWriter to match that.

### CODE REVIEW

**Comment by BigLep** [comment]
2022-08-26 triage conversation:
1. Just curious, @drgomesp how/where do you use this repo?
2. @hannahhoward do you know if/how this repo is used?
3. Assigning to IPLD triage for now.

**Comment by drgomesp** [comment]
Honestly @BigLep I was actually just experimenting with all the libraries and eventually got to this one. Correct me if I'm wrong, but it doesn't seem like this is used anywhere or at least on the main repos.

Would there be a more convenient/recommended way to interact with DAGs at the lowest possible level?

**Comment by rvagg** [comment]
oo, I didn't even know about this repo!

I don't think it's being used, although I'll get confirmation from @hannahhoward but I reckon we can archive this repo. I believe its functionality has since been replaced by the `storage` packages in go-ipld-prime now, particularly bsrvadapter: https://pkg.go.dev/github.com/ipld/go-ipld-prime/storage/bsrvadapter (there's other adapters for other [legacy] storage interfaces).

**Comment by rvagg** [comment]
OK, got feedback and this repo never ended up getting used for what it was intended for—part of the go-ipld-prime migration in go-ipfs. So I'm going to archive it.
But thanks for your contribution @drgomesp! I hope to see you around related repos. Sorry this couldn't go any further.

**Pull request closed without merging**
